Q1

In [7]:
import numpy as np
a=np.arange(1,13)
a_reshape=a.reshape(3,4)
print("数组维度（ndim）:", a_reshape.ndim)
print("数组形状（shape）:", a_reshape.shape)
print("元素总个数（size）:", a_reshape.size)
print("\n数组内容：")
print(a_reshape)

数组维度（ndim）: 2
数组形状（shape）: (3, 4)
元素总个数（size）: 12

数组内容：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Q2

In [8]:
# 1. 创建包含浮点数的数组
float_a = np.array([1.5, 2.6, 3.7, 4.8])
# 2. 转换为 32 位整数类型
int_a = float_a.astype(np.int32)
# 3. 打印转换前后的数组和数据类型
print("转换前数组：", float_a)
print("转换前数据类型：", float_a.dtype.name)
print("转换后数组：", int_a)
print("转换后数据类型：", int_a.dtype.name)

转换前数组： [1.5 2.6 3.7 4.8]
转换前数据类型： float64
转换后数组： [1 2 3 4]
转换后数据类型： int32


Q3

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sub_a = a[:2, 1:3]
print("原数组：")
print(a)
print("切片后的子数组：")
print(sub_a)
a[0:2,:2]

原数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
切片后的子数组：
[[2 3]
 [6 7]]


array([[1, 2],
       [5, 6]])

Q4

In [11]:
arr = np.array([10, 15, 20, 25, 30, 35])
# 1. 花式索引提取第1、3、5个元素（索引0,2,4）
fancy_index = arr[[0, 2, 4]]
# 2. 布尔索引提取大于20的元素
bool_index = arr[arr > 20]
print("原数组：", arr)
print("花式索引结果：", fancy_index)
print("布尔索引结果：", bool_index)

原数组： [10 15 20 25 30 35]
花式索引结果： [10 20 30]
布尔索引结果： [25 30 35]


Q5

In [ ]:
# 创建形状为(3,4)的全0数组
arr_a = np.zeros((3, 4))
# 创建一维数组
arr_b = np.array([1, 2, 3, 4])
# 利用广播机制相加
result = arr_a + arr_b
print("arr_a:\n", arr_a)
print("arr_b:\n", arr_b)
print("相加结果:\n", result)

arr_a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr_b:
 [1 2 3 4]
相加结果:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Q6

In [1]:
import numpy as np
# 1. 创建数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
# 2. 计算数组 x 中每个元素的平方根
sqrt_x = np.sqrt(x)
# 3. 计算对应位置上的最大值
max_result = np.maximum(sqrt_x, y)
print("数组 x：", x)
print("数组 y：", y)
print("x 的平方根：", sqrt_x)
print("对应位置的最大值：", max_result)

数组 x： [ 1  4  9 16]
数组 y： [2 1 4 5]
x 的平方根： [1. 2. 3. 4.]
对应位置的最大值： [2. 2. 4. 5.]


Q7

In [2]:
import numpy as np
# 创建形状为(2, 3, 4)的三维数组
arr = np.arange(24).reshape((2, 3, 4))
# 使用transpose()转换轴顺序为(1, 0, 2)
transposed_arr = arr.transpose((1, 0, 2))
# 打印转换后的形状
print("原数组形状：", arr.shape)
print("转置后数组形状：", transposed_arr.shape)

原数组形状： (2, 3, 4)
转置后数组形状： (3, 2, 4)


Q8

In [3]:
import numpy as np
# 创建题目给定的数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
# 使用 np.where() 进行条件选择
result = np.where(arr_con, arr_x, arr_y)
print("条件数组：", arr_con)
print("arr_x：", arr_x)
print("arr_y：", arr_y)
print("结果数组：", result)

条件数组： [ True False  True]
arr_x： [1 5 7]
arr_y： [2 6 8]
结果数组： [1 6 7]


Q9

In [4]:
import numpy as np
# 创建二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
# 1. 计算所有元素的算术平均值
mean_val = arr.mean()
# 2. 按列(axis=0)从小到大排序
arr_sorted = np.sort(arr, axis=0)
print("原数组：")
print(arr)
print("所有元素的算术平均值：", mean_val)
print("按列排序后的数组：")
print(arr_sorted)

原数组：
[[6 2 7]
 [3 6 2]
 [4 3 2]]
所有元素的算术平均值： 3.888888888888889
按列排序后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


Q10

In [5]:
import numpy as np
# 1. 设置随机数种子为10
np.random.seed(10)
# 2. 生成两个形状为(2,2)的[0,1)均匀分布随机矩阵A和B
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
# 3. 计算矩阵A和B的点积
dot_product = np.dot(A, B)
print("矩阵A：")
print(A)
print("矩阵B：")
print(B)
print("矩阵A和B的点积：")
print(dot_product)

矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
矩阵A和B的点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
